export const Endpoints = {
    baseUrl: 'http://localhost:3333',
    signUp: 'http://localhost:3333/auth/signup',
    signIn: 'http://localhost:3333/auth/signin',
    smartHome: '/smartHome',
    getUser: '/users/me',
    getCommands: '/commands',
    getOccupants: '/occupants',
    occupant: '/occupant',
    createOccupant: '/occupant/create',
    patchDoorCommand: '/doorCommand',
    getDoorStatus: '/doorStatus',
    getRooms: '/rooms',
    room: '/room',
    create: '/create',
}